import test from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';

test('DocumentScanner Automated Checks Post-Audit', async (t) => {
  const componentPath = path.join(process.cwd(), 'src/components/DocumentScanner.tsx');
  const componentCode = fs.readFileSync(componentPath, 'utf8');

  await t.test('inputs distincts et ids uniques, aucun ref.click nécessaire', () => {
    // Check for native label activation

    assert.match(componentCode, /<(label|div)[^>]*className="btn btn-primary scanner-btn-camera"/);

    // Check inputs are inside labels and not using ref.click for triggering
    assert.strictEqual(componentCode.includes('fileInputCameraRef.current?.click()'), false, 'Should not use ref.current?.click()');

    // Check for unique IDs generated by name
    assert.match(componentCode, /id=\{`\$\{name\}-camera`\}/);
    assert.match(componentCode, /id=\{`\$\{name\}-gallery`\}/);
    assert.match(componentCode, /id=\{`\$\{name\}-pdf`\}/);
  });

  await t.test('desktop ne présente pas caméra (pointer: coarse)', () => {
    // The CSS logic
    assert.match(componentCode, /@media \(pointer: coarse\) and \(hover: none\)/);
    assert.match(componentCode, /\.scanner-btn-camera\s*\{\s*display:\s*block;\s*\}/);
    assert.match(componentCode, /\.scanner-btn-desktop-only\s*\{\s*display:\s*inline\s*!important;\s*\}/);
  });

  await t.test('polygon sans % et calcul screen -> normalized avec zoom/pan', () => {
    assert.match(componentCode, /viewBox=\{`0 0 \$\{imgSize\.width\} \$\{imgSize\.height\}`\}/);
    assert.match(componentCode, /points=\{corners\.map\(c => `\$\{c\.x \* imgSize\.width\},\$\{c\.y \* imgSize\.height\}`\)\.join\(' '\)\}/);
    assert.strictEqual(componentCode.includes('%,'), false, 'SVG Polygon should not contain % coordinates');

    // screen -> normalized mapped with rect
    assert.match(componentCode, /let x = \(e\.clientX - rect\.left\) \/ rect\.width;/);
  });

  await t.test('MAX_PROCESS_DIMENSION', () => {
    assert.match(componentCode, /maxWidth:\s*2000,\s*maxHeight:\s*2000/);
  });

  await t.test('aucun submit scanner', () => {
    const formSubmitStr = 'type="submit"';
    assert.strictEqual(componentCode.includes(formSubmitStr), false, 'Component contains submit button');
  });

  await t.test('ObjectURL cleanup si testable', () => {
    assert.match(componentCode, /URL\.revokeObjectURL/);
  });

  await t.test('Visualiser/Modifier conserve corners', () => {
    assert.match(componentCode, /setScanMode\('PREVIEW'\)/);
    assert.match(componentCode, /setScanMode\('CROP'\)/);
    // There is no reset of corners when switching modes in the code
  });
});

test('Demande Devis page integration checks', async (t) => {
  const pagePath = path.join(process.cwd(), 'src/app/demande-devis/page.tsx');
  const pageCode = fs.readFileSync(pagePath, 'utf8');

  await t.test('Recto remplacé => Verso conservé and vice versa', () => {
    // The state for recto and verso are distinct useState calls
    assert.match(pageCode, /const \[rectoFile, setRectoFile\] = useState/);
    assert.match(pageCode, /const \[versoFile, setVersoFile\] = useState/);

    // Check they are rendered independently
    assert.match(pageCode, /onFileAccepted=\{setRectoFile\}/);
    assert.match(pageCode, /onFileAccepted=\{setVersoFile\}/);
  });
});
