import test from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';

test('DocumentScanner Automated Checks Post-Audit', async (t) => {
  const componentPath = path.join(process.cwd(), 'src/components/DocumentScanner.tsx');
  const componentCode = fs.readFileSync(componentPath, 'utf8');

  await t.test('inputs distincts et ids uniques, aucun ref.click nécessaire', () => {
    // Check for native label activation

    assert.match(componentCode, /<(label|div)[^>]*className="btn btn-primary scanner-btn-camera"/);

    // Check inputs are inside labels and not using ref.click for triggering
    assert.strictEqual(componentCode.includes('fileInputCameraRef.current?.click()'), false, 'Should not use ref.current?.click()');

    // Check for unique IDs generated by name
    assert.match(componentCode, /id=\{`\$\{name\}-camera`\}/);
    assert.match(componentCode, /id=\{`\$\{name\}-gallery`\}/);
    assert.match(componentCode, /id=\{`\$\{name\}-pdf`\}/);
  });

  await t.test('desktop ne présente pas caméra (pointer: coarse)', () => {
    // The CSS logic
    assert.match(componentCode, /@media \(pointer: coarse\) and \(hover: none\)/);
    assert.match(componentCode, /\.scanner-btn-camera\s*\{\s*display:\s*block;\s*\}/);
    assert.match(componentCode, /\.scanner-btn-desktop-only\s*\{\s*display:\s*inline\s*!important;\s*\}/);
  });

  await t.test('polygon sans % et calcul screen -> normalized avec zoom/pan', () => {
    assert.match(componentCode, /viewBox=\{`0 0 \$\{imgSize\.width\} \$\{imgSize\.height\}`\}/);
    assert.match(componentCode, /points=\{corners\.map\(c => `\$\{c\.x \* imgSize\.width\},\$\{c\.y \* imgSize\.height\}`\)\.join\(' '\)\}/);
    assert.strictEqual(componentCode.includes('%,'), false, 'SVG Polygon should not contain % coordinates');

    // screen -> normalized mapped with rect
    assert.match(componentCode, /let x = \(e\.clientX - rect\.left\) \/ rect\.width;/);
  });

  await t.test('MAX_PROCESS_DIMENSION', () => {
    assert.match(componentCode, /maxWidth:\s*2000,\s*maxHeight:\s*2000/);
  });

  await t.test('aucun submit scanner', () => {
    const formSubmitStr = 'type="submit"';
    assert.strictEqual(componentCode.includes(formSubmitStr), false, 'Component contains submit button');
  });

  await t.test('ObjectURL cleanup si testable', () => {
    assert.match(componentCode, /URL\.revokeObjectURL/);
  });

  await t.test('Visualiser/Modifier conserve corners', () => {
    assert.match(componentCode, /setScanMode\('PREVIEW'\)/);
    assert.match(componentCode, /setScanMode\('CROP'\)/);
    // There is no reset of corners when switching modes in the code
  });
});

test('DocumentScanner Fit Contain Logic', async (t) => {
  const computeFit = (vw: number, vh: number, sw: number, sh: number) => {
    const fitScale = Math.min(vw / sw, vh / sh);
    return { w: sw * fitScale, h: sh * fitScale };
  };

  await t.test('image portrait dans viewport paysage', () => {
    const res = computeFit(800, 400, 1000, 2000); // viewport large, image tall
    assert.strictEqual(res.w, 200); // 1000 * (400/2000)
    assert.strictEqual(res.h, 400); // max height
    assert.ok(res.w <= 800 && res.h <= 400, 'must fit within viewport');
  });

  await t.test('image paysage dans viewport portrait', () => {
    const res = computeFit(400, 800, 2000, 1000); // viewport tall, image wide
    assert.strictEqual(res.w, 400); // max width
    assert.strictEqual(res.h, 200); // 1000 * (400/2000)
    assert.ok(res.w <= 400 && res.h <= 800, 'must fit within viewport');
  });

  await t.test('image carrée', () => {
    const res = computeFit(300, 500, 1000, 1000);
    assert.strictEqual(res.w, 300);
    assert.strictEqual(res.h, 300);
    assert.ok(res.w <= 300 && res.h <= 500, 'must fit within viewport');
  });

  await t.test('aucun rendu > viewport', () => {
    const res = computeFit(390, 844, 4000, 3000);
    assert.ok(res.w <= 390);
    assert.ok(res.h <= 844);
  });
});

test('Demande Devis page integration checks', async (t) => {
  const pagePath = path.join(process.cwd(), 'src/app/demande-devis/page.tsx');
  const pageCode = fs.readFileSync(pagePath, 'utf8');

  await t.test('Recto remplacé => Verso conservé and vice versa', () => {
    // The state for recto and verso are distinct useState calls
    assert.match(pageCode, /const \[rectoFile, setRectoFile\] = useState/);
    assert.match(pageCode, /const \[versoFile, setVersoFile\] = useState/);

    // Check they are rendered independently
    assert.match(pageCode, /onFileAccepted=\{\(f\) => \{ setRectoFile\(f\); clearFieldError\('recto'\); \}\}/);
    assert.match(pageCode, /onFileAccepted=\{\(f\) => \{ setVersoFile\(f\); clearFieldError\('verso'\); \}\}/);
  });
});

test('DocumentScanner PDF and Size Limits Logic', async (t) => {
  const componentPath = path.join(process.cwd(), 'src/components/DocumentScanner.tsx');
  const componentCode = fs.readFileSync(componentPath, 'utf8');

  await t.test('CMC PDF 5 MB => rejet client immédiat, onFileAccepted NON appelé', () => {
    assert.match(componentCode, /if \(f\.type === 'application\/pdf' && isPdfOk\)/);
    assert.match(componentCode, /if \(f\.size > 4 \* 1024 \* 1024\)/);
    assert.match(componentCode, /setLocalError\("Le fichier ne doit pas dépasser 4 MB\."\)/);
    // Checking it returns before onFileAccepted
    assert.match(componentCode, /e\.target\.value = '';\s*return;/);
  });

  await t.test('JPEG/PNG source >4 MB mais <15 MB => toujours autorisé au scanner', () => {
    assert.match(componentCode, /if \(originalFile\.size > MAX_SOURCE_FILE_SIZE\)/);
    // 15 MB is MAX_SOURCE_FILE_SIZE
  });

  await t.test('image finale >4 MB => toujours rejetée', () => {
    assert.match(componentCode, /if \(blob\.size > MAX_FINAL_FILE_SIZE\)/);
  });
});

test('Pre-Submit Guard in page.tsx', async (t) => {
  const pagePath = path.join(process.cwd(), 'src/app/demande-devis/page.tsx');
  const pageCode = fs.readFileSync(pagePath, 'utf8');

  await t.test('pre-submit checks files > 4MB and prevents submit', () => {
    assert.match(pageCode, /const MAX_SIZE = 4 \* 1024 \* 1024;/);
    assert.match(pageCode, /sizeErrors\.cmc = "Le fichier ne doit pas dépasser 4 MB\."/);
    assert.match(pageCode, /sizeErrors\.recto = "Le fichier ne doit pas dépasser 4 MB\."/);
    assert.match(pageCode, /setFieldErrors\(prev => \(\{ \.\.\.prev, \.\.\.sizeErrors \}\)\);/);
    assert.match(pageCode, /setIsSubmitting\(false\);/);
    assert.match(pageCode, /return;/);
  });
});
